const userGuide = {
  "/games":
    'Die Seite "Spiele" zeigt eine Übersicht aller verfügbaren Quizspiele, die Sie spielen können. Jedes verfügbare Quiz wird in Form einer interaktiven Karte präsentiert, die nützliche Informationen bereitstellt. Darunter finden sich unter anderem: ' +
    "Quiztitel: Der Name des Quiz." +
    "Quizthema: Das Hauptthema oder die Kategorie des Quiz." +
    "Ersteller: Der Name des Erstellers des Quiz." +
    "Fragenanzahl: Die Anzahl der Fragen, die das Quiz enthält." +
    'Um ein Quiz zu starten, klicken Sie einfach auf die entsprechende Karte. Wenn Sie ein Quiz am selben Tag bereits gespielt haben, wird es zur einfacheren Organisation am Ende der Liste in einer Akkordeon-Komponente verborgen. Sie können diese Quizspiele einsehen, indem Sie auf die Schaltfläche "Heute bereits gespielte Quiz" klicken. Diese bereits gespielten Quizspiele werden als ausgegraute Kacheln dargestellt. Sie können diese Quiz erneut spielen, aber beachten Sie, dass Sie für ein am selben Tag wiederholtes Quiz keine weiteren Punkte erhalten. ',

  "/games/id":
    'Spielbeginn: Durch Auswahl einer Quizkarte werden Sie direkt zum Spiel geleitet. Fortschrittsanzeige: Am oberen Bildschirmrand finden Sie einen Fortschrittsbalken, der die Anzahl der bisher beantworteten Fragen im Verhältnis zur Gesamtzahl der Fragen anzeigt. Fragen und Antworten: Unter der Fortschrittsanzeige erscheint die aktuelle Frage mit vier Antwortmöglichkeiten. Wählen Sie eine Antwort aus, indem Sie auf die entsprechende Option klicken. Es gibt stets nur eine korrekte Antwort. Feedback zur Antwort: Ein animiertes Banner am unteren Bildschirmrand informiert Sie, ob Ihre Antwort richtig oder falsch war. Bei einer richtigen Antwort werden Sie automatisch zur nächsten Frage geführt. Hinweisoption: Zu einigen Fragen gibt es optionale Hinweise, die über ein Fragezeichensymbol neben der Frage aufgerufen werden können. Die Nutzung des Hinweises zieht jedoch einen Punktabzug nach sich. Spielende: Nach Beantwortung aller Fragen erscheint die "Spielende"-Ansicht. Hier erhalten Sie eine Zusammenfassung Ihrer Leistung, einschließlich der Anzahl der Fehler, der benötigten Zeit, der in Anspruch genommenen Hinweise und der erzielten Punkte, präsentiert in einer Tabelle. Fragenrückblick: Im unteren Bereich können Sie alle gestellten Fragen nochmals in Form von Karten einsehen. Der Rahmen der Karte zeigt mit der Farbgebung (rot für falsch, grün für richtig) das Ergebnis jeder Frage an. Durch Aufklappen der Karte erhalten Sie zusätzliche Informationen zur Frage. Feedback zur Frage: Über einen Button auf der Karte können Sie eine Frage zur Überprüfung melden, falls Sie faktische Ungenauigkeiten oder unangemessenen Inhalt vermuten. Zurück zur Auswahl: Unterhalb der Leistungstabelle befindet sich eine Schaltfläche, die Sie zurück zur Übersichtsseite der Quizspiele führt. ',

  "/create":
    'In diesem Abschnitt des Benutzerhandbuchs wird beschrieben, wie registrierte Nutzer ein neues Quiz anlegen können. Beginnen Sie damit, einen Titel und ein Thema für Ihr Quiz zu wählen. Ein Quiz muss darüber hinaus mindestens eine Frage beinhalten. Es gibt zwei Methoden, um Fragen hinzuzufügen: Import über JSON: Klicken Sie auf das Import-Symbol, um ein Eingabefenster zu öffnen. Hier können Sie Ihr JSON-Array einfügen und importieren. Manuelle Eingabe: Betätigen Sie den Button "Frage hinzufügen". Es öffnet sich ein Drawer mit einer Maske, in der Sie Ihre Frage und die dazugehörigen Antworten eintragen können. Mit dem Absenden über den "Submit"-Button wird Ihre Frage als Karte auf der "Quiz erstellen"-Seite hinzugefügt. Sobald Sie mit dem Erstellen des Quiz fertig sind, können Sie es durch Klicken des "Speichern"-Buttons oben rechts anlegen. Bitte beachten Sie, dass alle Eingaben validiert werden. Sollten Informationen fehlen oder Fehler vorliegen, wird dies durch ein animiertes Banner oder einen Hinweistext direkt unter dem betreffenden Eingabefeld signalisiert. ',

  "/admin":
    "Im Abschnitt „Admin-Bereich“, der ausschließlich angemeldeten Administratoren zugänglich ist, finden Sie eine Auflistung aller gemeldeten Fragen. Administratoren haben die Möglichkeit, jede Frage durch Klicken auf den Button „Löschen“ endgültig aus dem Quiz zu entfernen. Alternativ können Fragen durch Auswahl des Buttons „Freigeben“ als ungefährlich eingestuft und somit von der Meldeliste genommen werden. ",

  "/highscores":
    "Dieser Abschnitt ermöglicht es Ihnen, Ihre Leistungen mit anderen Spielern zu vergleichen. Über ein Dropdown-Menü haben Sie zwei Auswahlmöglichkeiten: 'Top 10 Spieler' oder ein spezifisches Themengebiet. Wenn Sie 'Top 10 Spieler' auswählen, wird eine Tabelle angezeigt, die die zehn besten Spieler nach ihrer Punktzahl auflistet. Bei der Auswahl eines Themengebiets erhalten Sie eine Übersicht über die Rangfolge der Spiele in diesem Bereich, sortiert nach ihrer Rangposition. ",

  "/log":
    "In der Sektion „Log“ erhalten Sie eine Übersicht der zuletzt gespielten Spiele, ergänzt um relevante Zusatzinformationen. Diese beinhalten Angaben zum Spieler, zum gespielten Quiz, zu den erlangten Punkten sowie zur benötigten Spielzeit. ",

  "/profil":
    "Das Benutzerprofil bietet eine visuelle Darstellung bestimmter Benutzerdaten, einschließlich der E-Mail-Adresse und Ihrer Benutzer-ID. Zusätzlich besteht die Option, den eigenen Nicknamen zu ändern – nähere Informationen hierzu finden Sie im Abschnitt 2.6.1 „Nickname anpassen“. Registrierte Nutzer haben darüber hinaus die Möglichkeit, ihr Konto eigenständig zu löschen. Nickname anpassen Im Bereich des Benutzerprofils finden Sie neben dem Nicknamen ein kleines Stift-Symbol, das als Button dient. Mit einem Klick auf dieses Symbol öffnet sich ein Dialogfenster (Drawer), in dem Sie Ihren Nicknamen ändern können. Nachdem der neue Nickname eingegeben und abgesendet wurde, erfolgt eine Überprüfung auf Einzigartigkeit. Sollte der Name bereits vergeben sein, wird der Nutzer durch eine entsprechende Meldung informiert. Es gibt zudem weitere Einschränkungen hinsichtlich der Nutzung von Sonderzeichen, die durch Warnmeldungen visualisiert werden, falls solche Zeichen verwendet werden. ",

  "/login":
    "Wenn Sie nicht angemeldet sind, können Sie über einen Klick auf das Benutzermenü zum Eintrag „Login“ gelangen (siehe Abbildung 1). Dieser leitet Sie zur Login-Seite weiter. Für die Anmeldung sind die E-Mail-Adresse und das Passwort erforderlich. Nach erfolgreichem Login werden Sie zur Startseite weitergeleitet. Sollte es zu einem Fehler kommen, wird dies über eine Warnmeldung angezeigt. ",

  "/register":
    "Wenn Sie noch keinen Account haben, können Sie sich über die Option „Registrieren“ ein neues Konto anlegen. Die Option finden Sie im Benutzermenü, solange Sie noch nicht angemeldet sind (siehe Abbildung 1). Nach der Registrierung erhalten Sie eine E-Mail mit einem Bestätigungslink an Ihre angegebene E-Mail-Adresse. Durch Anklicken des Bestätigungslinks verifizieren Sie Ihre E-Mail-Adresse. Anschließend werden Sie automatisch zur Login-Seite weitergeleitet, womit die Registrierung abgeschlossen ist. ",
};

export default userGuide;
